version: "3.7"
services:
{% if minio_cluster_mode is not defined %}
  traefik:
    image: traefik:{{ traefik_tag }}
    container_name: traefik
    restart: unless-stopped
    dns: 8.8.8.8
    command:
      - --entryPoints.web.address=:80
      - --entryPoints.minio.address=:9000
      - --entryPoints.websecure.address=:443
      - --providers.docker.exposedByDefault=false
      - --certificatesResolvers.letsencrypt.acme.email=infrastructure@barfoot.co.nz
      - --certificatesResolvers.letsencrypt.acme.storage=/etc/traefik/acme.json
      - --certificatesResolvers.letsencrypt.acme.dnsChallenge.provider=cloudflare
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --providers.file.filename=/data/traefik.toml
      #- --certificatesResolvers.letsencrypt.acme.caServer=https://acme-staging-v02.api.letsencrypt.org/directory
      #- --api.insecure
      #- --log.level=DEBUG
      #- --accesslog
    ports:
      - 80:80
      - 443:443
      #- 8080:8080
    environment:
      - CF_DNS_API_TOKEN=$CF_DNS_API_TOKEN
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /mnt/docker/traefik:/etc/traefik
      - ./traefik.toml:/data/traefik.toml
    logging:
      driver: local
{% endif %}    
  minio:
    container_name: minio
    image: minio/minio:{{ minio_tag }}
    restart: unless-stopped
    command: server {{ minio_export }} --console-address :9001
{% if minio_cluster_mode is defined %}
    ports:
      - 9000:9000
      - 9001:9001
{% endif %}
    environment:
      - MINIO_ROOT_USER=$MINIO_ROOT_USER
      - MINIO_ROOT_PASSWORD=$MINIO_ROOT_PASSWORD
      - MINIO_BROWSER_REDIRECT_URL=https://{{ mc_sub_domain }}.barfoot.co.nz
      - MINIO_SERVER_URL=https://{{ minio_sub_domain }}.barfoot.co.nz
{% if minio_cluster_mode is not defined %}
      - MINIO_IDENTITY_LDAP_LOOKUP_BIND_DN=$MINIO_IDENTITY_LDAP_LOOKUP_BIND_DN
      - MINIO_IDENTITY_LDAP_LOOKUP_BIND_PASSWORD=$MINIO_IDENTITY_LDAP_LOOKUP_BIND_PASSWORD
      - MINIO_IDENTITY_LDAP_USER_DN_SEARCH_BASE_DN={{ ldap_search_base }}
      - MINIO_IDENTITY_LDAP_USER_DN_SEARCH_FILTER=(&(objectCategory=user)(sAMAccountName=%s))
      - MINIO_IDENTITY_LDAP_SERVER_ADDR=$MINIO_IDENTITY_LDAP_SERVER_ADDR
      - MINIO_IDENTITY_LDAP_TLS_SKIP_VERIFY=on
      - MINIO_IDENTITY_LDAP_GROUP_SEARCH_BASE_DN={{ ldap_search_base }}
      - MINIO_IDENTITY_LDAP_GROUP_SEARCH_FILTER=(&(objectCategory=group)(member:1.2.840.113556.1.4.1941:=%d))
{% endif %}
    volumes:
      - /mnt/data:/export
      - /mnt/docker/minio/config:/root/.minio
    logging:
      driver: local
{% if minio_cluster_mode is not defined %}
    depends_on:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.minio.rule=Host(`{{ minio_sub_domain }}.barfoot.co.nz`)"
      - "traefik.http.routers.minio.entrypoints=websecure"
      - "traefik.http.routers.minio.tls.certresolver=letsencrypt"
      - "traefik.http.routers.minio.tls.domains[0].main={{ minio_main_for_sans }}.barfoot.co.nz"
      - "traefik.http.routers.minio.tls.domains[0].sans={{ minio_sub_domain }}.barfoot.co.nz,{{ mc_sub_domain }}.barfoot.co.nz"
      - "traefik.http.routers.minio.service=minio"
      - "traefik.http.services.minio.loadbalancer.server.port=9000"
      - "traefik.http.routers.console.rule=Host(`{{ mc_sub_domain }}.barfoot.co.nz`)"
      - "traefik.http.routers.console.entrypoints=websecure"
      - "traefik.http.routers.console.tls.certresolver=letsencrypt"
      - "traefik.http.routers.cosnole.tls.domains[0].main={{ minio_main_for_sans }}.barfoot.co.nz"
      - "traefik.http.routers.console.tls.domains[0].sans={{ minio_sub_domain }}.barfoot.co.nz,{{ mc_sub_domain }}.barfoot.co.nz"
      - "traefik.http.routers.console.service=console"
      - "traefik.http.services.console.loadbalancer.server.port=9001"
{% endif %}      
