- name: Block
  block:
    - name: Drain node
      ansible.builtin.command: kubectl --kubeconfig /etc/kubernetes/admin.conf drain {{ inventory_hostname.split(".")[0] }} --ignore-daemonsets --delete-local-data
      become: true
      delegate_to: "{{ master }}"

    - name: Reboot node
      become: true
      ansible.builtin.reboot:
        reboot_timeout: 600

    - name: Uncordon node
      ansible.builtin.command: kubectl --kubeconfig /etc/kubernetes/admin.conf uncordon {{ inventory_hostname.split(".")[0] }}
      become: true
      delegate_to: "{{ master }}"
