---
# handlers file for docker_engine
- name: Docker_engine_reconfigure
  become: true
  become_user: root
  when: docker_engine_manage_service and docker_engine_config_reload and docker_engine_eff_init == 'systemd'
  ansible.builtin.systemd:
    daemon_reload: true
- name: Docker_engine_restart
  become: true
  become_user: root
  when: docker_engine_manage_service and docker_engine_config_reload
  ansible.builtin.service:
    name: docker
    state: restarted
