apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik
  namespace: traefik
data:
  traefik.toml: |
    [http.middlewares.f5-ipwhitelist.ipWhiteList]
    {% if f5_ip != None %}
    sourceRange = ["{{ f5_ip }}"]
    {% endif %}
    [tls.stores]
      [tls.stores.default]
        [tls.stores.default.defaultCertificate]
          certFile = "/data2/cert.pem"
          keyFile  = "/data2/cert.key"
    [tls.options.default]
    minVersion = "VersionTLS12"
    cipherSuites = [
    "TLS_AES_128_GCM_SHA256",
    "TLS_AES_256_GCM_SHA384",
    "TLS_CHACHA20_POLY1305_SHA256",
    "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
    "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
    "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
    "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256",
    "TLS_RSA_WITH_AES_256_GCM_SHA384"
    ]
  cert.pem: |
    {{ traefik_cert }}
  cert.key: |
    {{ traefik_cert_key }}
