---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  annotations:
  name: cert-manager
  namespace: kube-system
spec:
  targetNamespace: cert-manager
  repo: https://charts.jetstack.io
  chart: cert-manager
  version: "{{ cert_manager_chart_version }}"
  valuesContent: |-
    installCRDs: true
    extraArgs:
    - --dns01-recursive-nameservers-only
    - --dns01-recursive-nameservers=8.8.8.8:53,1.1.1.1:53
