- name: Upload a file to google dirive
  ansible.builtin.script: upload.ps1 -RefreshToken '{{ google_refresh_token }}' -ClientID '{{ google_client_id }}' -ClientSecret '{{ google_client_secret }}' -Folders '{{ google_folder_ids | join(",") }}' -SourceFile '{{ file_path_to_upload }}' -TargetFile '{{ target_filename }}' -SourceMime '{{ source_mime }}' -TargetMime '{{ target_mime }}'
  delegate_to: localhost
