- name: Disable upgrade of postgresql
  become: true
  ansible.builtin.command: apt-mark hold *postgres*

- name: Update all installed packages using APT module
  become: true
  ansible.builtin.apt:
    name: '*'
    state: latest
    update_cache: true
    only_upgrade: true

- name: Remove packages not needed anymore
  become: true
  ansible.builtin.apt:
    autoremove: true
