EXEC sp_CONFIGURE 'show advanced options', '1'
RECONFIGURE
EXEC sp_CONFIGURE 'access check cache bucket count', '0'
EXEC sp_CONFIGURE 'access check cache quota', '0'
EXEC sp_CONFIGURE 'Ad Hoc Distributed Queries', '0'
EXEC sp_CONFIGURE 'affinity I/O mask', '0'
EXEC sp_CONFIGURE 'affinity mask', '0'
EXEC sp_CONFIGURE 'affinity64 I/O mask', '0'
EXEC sp_CONFIGURE 'affinity64 mask', '0'
EXEC sp_CONFIGURE 'Agent XPs', '1'
EXEC sp_CONFIGURE 'allow updates', '0'
EXEC sp_CONFIGURE 'backup checksum default', '0'
EXEC sp_CONFIGURE 'backup compression default', '1'
EXEC sp_CONFIGURE 'blocked process threshold (s)', '0'
EXEC sp_CONFIGURE 'c2 audit mode', '0'
EXEC sp_CONFIGURE 'clr enabled', '0'
EXEC sp_CONFIGURE 'contained database authentication', '0'
EXEC sp_CONFIGURE 'cost threshold for parallelism', '5'
EXEC sp_CONFIGURE 'cross db ownership chaining', '0'
EXEC sp_CONFIGURE 'cursor threshold', '-1'
EXEC sp_CONFIGURE 'Database Mail XPs', '0'
EXEC sp_CONFIGURE 'default full-text language', '1033'
EXEC sp_CONFIGURE 'default language', '0'
EXEC sp_CONFIGURE 'default trace enabled', '1'
EXEC sp_CONFIGURE 'disallow results from triggers', '0'
EXEC sp_CONFIGURE 'filestream access level', '0'
EXEC sp_CONFIGURE 'fill factor (%)', '0'
EXEC sp_CONFIGURE 'ft crawl bandwidth (max)', '100'
EXEC sp_CONFIGURE 'ft crawl bandwidth (min)', '0'
EXEC sp_CONFIGURE 'ft notify bandwidth (max)', '100'
EXEC sp_CONFIGURE 'ft notify bandwidth (min)', '0'
EXEC sp_CONFIGURE 'index create memory (KB)', '0'
EXEC sp_CONFIGURE 'in-doubt xact resolution', '0'
EXEC sp_CONFIGURE 'lightweight pooling', '0'
EXEC sp_CONFIGURE 'locks', '0'
EXEC sp_CONFIGURE 'max degree of parallelism', '0'
EXEC sp_CONFIGURE 'max full-text crawl range', '4'
EXEC sp_CONFIGURE 'max server memory (MB)', '2147483647'
EXEC sp_CONFIGURE 'max text repl size (B)', '-1'
EXEC sp_CONFIGURE 'max worker threads', '0'
EXEC sp_CONFIGURE 'media retention', '0'
EXEC sp_CONFIGURE 'min memory per query (KB)', '1024'
EXEC sp_CONFIGURE 'min server memory (MB)', '0'
EXEC sp_CONFIGURE 'nested triggers', '1'
EXEC sp_CONFIGURE 'network packet size (B)', '4096'
EXEC sp_CONFIGURE 'Ole Automation Procedures', '1'
EXEC sp_CONFIGURE 'open objects', '0'
EXEC sp_CONFIGURE 'optimize for ad hoc workloads', '1'
EXEC sp_CONFIGURE 'PH timeout (s)', '60'
EXEC sp_CONFIGURE 'precompute rank', '0'
EXEC sp_CONFIGURE 'priority boost', '0'
EXEC sp_CONFIGURE 'query governor cost limit', '0'
EXEC sp_CONFIGURE 'query wait (s)', '-1'
EXEC sp_CONFIGURE 'recovery interval (min)', '0'
EXEC sp_CONFIGURE 'remote access', '1'
EXEC sp_CONFIGURE 'remote admin connections', '1'
EXEC sp_CONFIGURE 'remote login timeout (s)', '10'
EXEC sp_CONFIGURE 'remote proc trans', '0'
EXEC sp_CONFIGURE 'remote query timeout (s)', '600'
EXEC sp_CONFIGURE 'Replication XPs', '0'
EXEC sp_CONFIGURE 'scan for startup procs', '0'
EXEC sp_CONFIGURE 'server trigger recursion', '1'
EXEC sp_CONFIGURE 'set working set size', '0'
EXEC sp_CONFIGURE 'show advanced options', '1'
EXEC sp_CONFIGURE 'SMO and DMO XPs', '1'
EXEC sp_CONFIGURE 'transform noise words', '0'
EXEC sp_CONFIGURE 'two digit year cutoff', '2049'
EXEC sp_CONFIGURE 'user connections', '0'
EXEC sp_CONFIGURE 'user options', '0'
EXEC sp_CONFIGURE 'xp_cmdshell', '0'
RECONFIGURE WITH OVERRIDE;
EXEC xp_instance_regwrite N'HKEY_LOCAL_MACHINE', N'Software\Microsoft\MSSQLServer\MSSQLServer', N'LoginMode', REG_DWORD, 2;
CREATE LOGIN [%domain%\SQL Admins] FROM WINDOWS WITH DEFAULT_DATABASE=[master]
ALTER SERVER ROLE [sysadmin] ADD MEMBER [%domain%\SQL Admins]
DROP LOGIN [BUILTIN\Administrators]
