DECLARE @CPUCOUNT AS INT
DECLARE @TEMPDBLOC AS NVARCHAR(250)
DECLARE @TEMPDBLOCNEW AS NVARCHAR(250)
DECLARE @TEMPDBNAME AS NVARCHAR(30)
DECLARE @TEMPDBNAMENEW AS NVARCHAR(30)
DECLARE @SQL AS NVARCHAR(max)

SET @TEMPDBNAME = 'tempdev'
SET @CPUCOUNT = (SELECT cpu_count FROM master.sys.dm_os_sys_info)
SET @TEMPDBLOC = (SELECT physical_name FROM tempdb.sys.database_files WHERE name = @TEMPDBNAME)
SET @TEMPDBLOC = LEFT(@TEMPDBLOC, LEN(@TEMPDBLOC) - 4)

USE master
IF @CPUCOUNT = 2
	begin
	PRINT 'CPU COUNT = 2'
	
	PRINT 'Adding 2nd tempdb datafile'
	SET @TEMPDBNAMENEW = @TEMPDBNAME + '2'
	SET @TEMPDBLOCNEW = @TEMPDBLOC + '2.mdf'
	
	SET @SQL = 'ALTER DATABASE tempdb
	Add File( Name = ' + QUOTENAME(@TEMPDBNAMENEW, '''') + '
	, FILENAME = ' + QUOTENAME(@TEMPDBLOCNEW,'''') + '
	, SIZE = 8MB
	, MAXSIZE = UNLIMITED
	, FILEGROWTH = 10%)'
		
	EXEC(@SQL)
	end
IF @CPUCOUNT = 3
	begin
	PRINT 'CPU COUNT = 3'
	
	PRINT 'Adding 2nd tempdb datafile'
	SET @TEMPDBNAMENEW = @TEMPDBNAME + '2'
	SET @TEMPDBLOCNEW = @TEMPDBLOC + '2.mdf'

	SET @SQL = 'ALTER DATABASE tempdb
	Add File( Name = ' + QUOTENAME(@TEMPDBNAMENEW, '''') + '
	, FILENAME = ' + QUOTENAME(@TEMPDBLOCNEW,'''') + '
	, SIZE = 8MB
	, MAXSIZE = UNLIMITED
	, FILEGROWTH = 10%)'

	EXEC(@SQL)

	PRINT 'Adding 3rd tempdb datafile'
	SET @TEMPDBNAMENEW = @TEMPDBNAME + '3'
	SET @TEMPDBLOCNEW = @TEMPDBLOC + '3.mdf'

	SET @SQL = 'ALTER DATABASE tempdb
	Add File( Name = ' + QUOTENAME(@TEMPDBNAMENEW, '''') + '
	, FILENAME = ' + QUOTENAME(@TEMPDBLOCNEW,'''') + '
	, SIZE = 8MB
	, MAXSIZE = UNLIMITED
	, FILEGROWTH = 10%)'

	EXEC(@SQL)
	end
IF @CPUCOUNT > 3
	begin
	PRINT 'CPU COUNT greater than 3'

	PRINT 'Adding 2nd tempdb datafile'
	SET @TEMPDBNAMENEW = @TEMPDBNAME + '2'
	SET @TEMPDBLOCNEW = @TEMPDBLOC + '2.mdf'
	
	SET @SQL = 'ALTER DATABASE tempdb
	Add File( Name = ' + QUOTENAME(@TEMPDBNAMENEW, '''') + '
	, FILENAME = ' + QUOTENAME(@TEMPDBLOCNEW,'''') + '
	, SIZE = 8MB
	, MAXSIZE = UNLIMITED
	, FILEGROWTH = 10%)'

	EXEC(@SQL)

	PRINT 'Adding 3rd tempdb datafile'
	SET @TEMPDBNAMENEW = @TEMPDBNAME + '3'
	SET @TEMPDBLOCNEW = @TEMPDBLOC + '3.mdf'
	
	SET @SQL = 'ALTER DATABASE tempdb
	Add File( Name = ' + QUOTENAME(@TEMPDBNAMENEW, '''') + '
	, FILENAME = ' + QUOTENAME(@TEMPDBLOCNEW,'''') + '
	, SIZE = 8MB
	, MAXSIZE = UNLIMITED
	, FILEGROWTH = 10%)'

	EXEC(@SQL)

	PRINT 'Adding 4th tempdb datafile'
	SET @TEMPDBNAMENEW = @TEMPDBNAME + '4'
	SET @TEMPDBLOCNEW = @TEMPDBLOC + '4.mdf'
	
	SET @SQL = 'ALTER DATABASE tempdb
	Add File( Name = ' + QUOTENAME(@TEMPDBNAMENEW, '''') + '
	, FILENAME = ' + QUOTENAME(@TEMPDBLOCNEW,'''') + '
	, SIZE = 8MB
	, MAXSIZE = UNLIMITED
	, FILEGROWTH = 10%)'

	EXEC(@SQL)
	end