---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: "{{ backup_pv }}"
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: "{{ backup_size }}"
  local:
    path: "{{ local_stoarage_path }}/{{ backup_pv }}"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - "{{ vmware_vmname }}"
  persistentVolumeReclaimPolicy: Delete
  volumeMode: Filesystem
  storageClassName: "{{ storage_class }}"
