apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: awx-ee-data
  namespace: {{ awx_namespace }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: "{{ ee_storage_size }}"
  storageClassName: "{{ storage_class }}"
