- name: Run sensitive variables report
  ansible.builtin.script: getvarnames.ps1 -apiKey '{{ octopus_api_key }}' -varFileName '{{ output_file_name}}' -server '{{ octopus_server_url }}'
  delegate_to: localhost
