vmware_vmname: p-in-vault-01
vmware_domain: barfoot.co.nz
vmware_network: DMZ Back End
vmware_ip: 192.168.6.38
vmware_team: Infrastructure
vmware_annotation: Main Hashicorp Vault instance
vmware_template_name: template-ubuntu-2004-server-base
vmware_num_cpus: "2"
vmware_memory_gb: 4
vmware_disk_gb: "16"
vmware_folder: /Production/Docker
vmware_datacentre: DC01
vmware_datastore: DC01-SSD-05

vmware_custom_attributes:
- ResticSchedule1

platform_roles:
- linux-docker

# Variables for the blueprint
traefik_tag: v2.6.6
vault_tag: "1.10.2"
vault_frontend: vault.barfoot.co.nz
vault_host: p-in-vault-01.barfoot.co.nz
vault_unseal_tag: latest

secrets:
- secret_mount: Production
  secret_path: Infrastructure/vault/vault.barfoot.co.nz
  secret_key: key
  engine_version: "2"
  variable_name: vault_unseal_key
- secret_mount: Production
  secret_path: Infrastructure/cloudflare/cert-manager
  secret_key: token
  engine_version: "2"
  variable_name: cloudflare_token
git_apply:
- name: configs
  git_repo: git@github.com:BarfootThompson/awx-playbooks.git
  git_directory: blueprints/docker/vault
  git_private_key: "{{ git_private_key }}"
  git_version: "{{ git_version }}"
  manifests_target_directory: ~/manifests_rendered
  manifests_recurse: Yes
  manifests_patterns: "*"
  apply_command:
- name: docker-compose
  # This is the git repo with your manifests. Use git protocol, not https
  git_repo: git@github.com:BarfootThompson/awx-playbooks.git
  # This is the directory inside the repo (without leading slash) where the manifests are
  git_directory: blueprints/docker/vault
  # This is the private key for the git repo
  git_private_key: "{{ git_private_key }}"
  # This specifies branch/tag/commit hash to switch to after cloning
  git_version: "{{ git_version }}"
  # This is where redndered manifest tempaltes end up
  manifests_target_directory: ~/manifests_rendered
  # This specifies if we want to get manifests from subfolders too
  manifests_recurse: Yes
  # Search pattern for the manifests like *.yml
  manifests_patterns: docker-compose.yaml
  # This is the command executed on the target to apply the file
  apply_command: docker compose -f "{{ apply_target_path }}" up -d --force-recreate

#mode: no_persistance
#mode: setup_backup
# used in setup_backup mode
#setup_backup:
#  #keep this value always
#  date: "{{ lookup('pipe','TZ=Pacific/Auckland date') }}"
#  #if you are running in the setup_backup mode you ususally need to sepcify path(s) to backup (comma-separate,no extra spaces)
#  backup_paths: /mnt/docker/vault/data
#  #you only need this if your repository suffix in minio is different from VM name (e.g. for vault)
#  repository_suffix: vault.barfoot.co.nz
#  #pathes to exclude from backup, space separated
#  exclusion_paths:
#  pre_backup_script: ~/manifests_rendered/backup/pre-backup.sh
#  post_backup_script: ~/manifests_rendered/backup/post-backup.sh
mode: restore
# used in restore mode
restic_snapshot_to_restore: latest
restic_backup_hostname: p-in-vault-02
