vmware_vmname: p-in-certmgr-01
vmware_domain: barfoot.co.nz
vmware_network: Admin Network
vmware_ip: 192.168.6.52
vmware_team: Infrastructure
vmware_annotation: Cert manager for renewing barfoot LE certificates
vmware_template_name: template-ubuntu-2004-server-base
vmware_num_cpus: "2"
vmware_memory_gb: 8
vmware_disk_gb: "32"
vmware_folder: /Production/K3s
vmware_datacentre: DC01
vmware_datastore: DC01-SSD-05

#vmware_custom_attributes:
#- ResticSchedule1

platform_roles:
- k3s

# Variable for platform
dns_zones:
- barfoot.co.nz
# Variables for the blueprint
cluster_issuer: letsencrypt
wildcard_domain: barfoot.co.nz
skip_wildcard: false
additional_subdomains:
- 7b12dacf26564a8ea230941337faf0e4.nonprod.finance
- 4d349b65332e477fbd070da59378a8d6.finance
cert_manager_chart_version: "1.8.0"
cert_manager_verifier_version: "0.2.0"
k3s_version: v1.23.6+k3s1

secrets:
- secret_mount: Production
  secret_path: Infrastructure/cloudflare/cert-manager
  secret_key: token
  engine_version: "2"
  variable_name: cloudflare_token
git_apply:
- name: init.sh
  git_repo: git@github.com:BarfootThompson/awx-playbooks.git
  git_directory: blueprints/kubernetes/cert-wildcard
  git_private_key: "{{ git_private_key }}"
  git_version: "{{ git_version }}"
  manifests_target_directory: ~/manifests_rendered
  manifests_recurse: Yes
  manifests_patterns: init.sh
  apply_command: bash "{{ apply_target_path }}"
- name: kubectl
  # This is the git repo with your manifests. Use git protocol, not https
  git_repo: git@github.com:BarfootThompson/awx-playbooks.git
  # This is the directory inside the repo (without leading slash) where the manifests are
  git_directory: blueprints/kubernetes/cert-wildcard
  # This is the private key for the git repo
  git_private_key: "{{ git_private_key }}"
  # This specifies branch/tag/commit hash to switch to after cloning
  git_version: "{{ git_version }}"
  # This is where redndered manifest tempaltes end up
  manifests_target_directory: ~/manifests_rendered
  # This specifies if we want to get manifests from subfolders too
  manifests_recurse: Yes
  # Search pattern for the manifests like *.yml
  manifests_patterns: "*.yml"
  # This is the command executed on the target to apply the file
  apply_command: kubectl apply -f "{{ apply_target_path }}"

#mode: setup_backup
#mode: restore
mode: no_persistance
# used in setup_backup mode
#setup_backup:
#  #keep this value always
#  date: "{{ lookup('pipe','TZ=Pacific/Auckland date') }}"
#  #if you are running in the setup_backup mode you ususally need to sepcify path(s) to backup (comma-separate,no extra spaces)
#  backup_paths:
#  #you only need this if your repository suffix in minio is different from VM name (e.g. for vault)
#  repository_suffix:
#  #pathes to exclude from backup, space separated
#  exclusion_paths:
#  pre_backup_script:
#  post_backup_script:
# used in restore mode
#restic_snapshot_to_restore: latest
